### ISSUE TITLE
No newline after title in index.md breaks language samples tabs.

### ISSUE THREAD

**Issue by Hauk** [Mermade/widdershins#11]
Hi Mike,

I hope this is not just a configuration issue on my part, so a pre-apology from me if I just PEBKAC'd.

I've been working on a small project to automate the conversion of Swagger JSON to Slate documentation, and I'm using Widdershins to convert the JSON to markdown. This then gets converted to Slate markup using this node module:

https://github.com/jmanek/slate_node

I'm using:

Node v6.9.5
NPM 4.3.0.

To generate the JSON, I'm using the following plugin in Eclipse: 

https://github.com/kongchen/swagger-maven-plugin

This produces this JSON output:

```json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a description",
    "version" : "1.1.1.1",
    "title" : "This is a title",
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "http://somesite.com:8080",
  "tags" : [ {
    "name" : "service"
  } ],
  "schemes" : [ "http", "https" ],
  "paths" : {
    "/something/list" : {
      "get" : {
        "tags" : [ "service" ],
        "summary" : "Some random summary.",
        "description" : "Some random description.",
        "operationId" : "list",
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/SomeObject"
            }
          },
          "500" : {
            "description" : "Unable to fetch list."
          }
        },
        "security" : [ {
          "api_key" : [ ]
        }, {
          "media_auth" : [ "read:something", "write:something" ]
        } ]
      }
    }
  },
  "definitions" : {
    "SomeObject" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int32"
        },
        "name" : {
          "type" : "string"
        },
        "layout" : {
          "type" : "string"
        }
      }
    }
  }
}
```

I then convert the testoutput.json file to markdown using Widdershins, with the following command:

```bash
node/node node_modules/widdershins/widdershins /var/tmp/testoutput.json -o /var/tmp/index.md
```

This produces the index.md file attached.

When I view the markup produced by Slate Node, the language samples tabs aren't shown. Example here:

![language_tabs_not_shown](https://cloud.githubusercontent.com/assets/243723/23283786/dde5a27e-fa1f-11e6-826d-489c519be8a1.png)

However, if I edit the index.md and add a newline after the title, the language tabs get shown.

E.g(broken).
```
---
title: This is a title v1.1.1.1
language_tabs:
  - shell: Shell
  - http: HTTP
  - html: JavaScript
  - javascript: Node.JS
  - python: Python
  - ruby: Ruby
  - java: Java
toc_footers: []
includes: []
search: true
highlight_theme: darkula
---
```
to(fixed): 

```
---
title: This is a title v1.1.1.1

language_tabs:
  - shell: Shell
  - http: HTTP
  - html: JavaScript
  - javascript: Node.JS
  - python: Python
  - ruby: Ruby
  - java: Java
toc_footers: []
includes: []
search: true
highlight_theme: darkula
---
```

Generating the Slate markup from the altered index.md with the newline after the title generates the language tabs as expected. Example here:

![language_tabs_shown](https://cloud.githubusercontent.com/assets/243723/23284017/1038e8a2-fa21-11e6-912a-6891944bb12a.png)

I've debugged into Slate Node and if I console.log the token(line 66) in marked.js I get the following output when I generate the markup without the newline in the index.md:

```
{ type: 'paragraph',
  text: 'title: This is a title v1.1.1.1\nlanguage_tabs:' }
{ type: 'list_start', ordered: false }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'text', text: 'includes: []' }
{ type: 'text', text: 'search: true' }
{ type: 'text', text: 'highlight_theme: darkula' }
{ type: 'list_item_end' }
{ type: 'list_end' }
```
When I generate it with the newline in the index.md it gives me the well formed data, which fixes the language tabs not showing. Here it is properly generated:

```
{ type: 'paragraph', text: 'title: This is a title v1.1.1.1' }
{ type: 'paragraph', text: 'language_tabs:' }
{ type: 'list_start', ordered: false }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'list_item_start' }
{ type: 'text', text: 'includes: []' }
{ type: 'text', text: 'search: true' }
{ type: 'text', text: 'highlight_theme: darkula' }
{ type: 'list_item_end' }
{ type: 'list_end' }
```

I think this might be a bug, but if I'm wrong please feel free to close the issue. Thanks for a great plugin! :)

Kind regards,
Eoghan
