### ISSUE TITLE
Flatten newline into <br>

### ISSUE THREAD

**Issue by revilwang** [Mermade/widdershins#211]
**Is your feature request related to a problem? Please describe.**

When transform OpenAPI3 specs, the newline `'\n'` characters in long description are flattened to blank spaces, which leads to description cell really hard to read.

**Describe the solution you'd like**

I would suggest that blank space is flattened into `<br>` so that the original format is preserved.

**Describe alternatives you've considered**

Or provides a configuration to allow so

**Comment by MikeRalphson** [comment]
Interesting. Can you show a fragment of your OpenAPI document so I can see how the `\n` characters appear, i.e. to make sure the line-breaks are not just YAML formatting etc?

Then I'll have a play and see how things look.

**Comment by revilwang** [comment]
OpenAPI specs says the description can be written as CommonMark format, and we utilize this function a lot. One of my schema component has a field defined as below:

```yaml
status:
  type: string
  readOnly: true
  enum:
    - open
    - close
  description: |
      Order status

      - `open`: waiting to be traded
      - `finished`: finished
```

But in the Markdown file widdershins generated is shown as below:

```
|status|string|false|read-only|Order status  - `open`: waiting to be traded - `finished`: finished|
```

The newline characters are flattened to blank space. If I manually edit the blank space to `<br>`. The format defined in OpenAPI documents is preserved in slate
