### ISSUE TITLE
Is it possible to remove the auto generated header at the top of the markdown file?

### ISSUE THREAD

**Issue by pbacon-blaber** [Mermade/widdershins#230]
I was wondering if it's possible to remove the "header" that's getting generated at the top of the output markdown file?

```
---
title: my_app
language_tabs:
  - shell: Shell
  - http: HTTP
  - javascript: JavaScript
  - javascript--nodejs: Node.JS
  - ruby: Ruby
  - python: Python
  - java: Java
  - go: Go
toc_footers: []
includes: []
search: true
highlight_theme: darkula
headingLevel: 2

---
```

I'm using custom user templates as I just would like to generate a plain markdown file, but haven't been able to figure out how to remove this from the top.
