### ISSUE TITLE
NodeJS Snippets with HTTPSnippets not formatted correctly

### ISSUE THREAD

**Issue by Hydragyrum** [Mermade/widdershins#284]
**Describe the bug**
A clear and concise description of what the bug is. Reports containing a full reproduction recipe (command-line and input file gist) will get a **much** faster response.

Possibly related to #189 but generated code for nodeJS is fenced in a `node` block in the markdown, and I'm not sure the markdown engine understands that very well. As a result, the block is rendered as plaintext and is shown on every sample tab.

* [x] - I have checked that my input document is valid OpenAPI 2.0/3.0.x or AsyncAPI 1.x

**To Reproduce**
1. Command-line:
`widdershins -e widdershins-opts.yaml test.yaml -o test.md`

2. My input file: (please link to a gist)
```yaml
openapi: 3.0.2
info:
  title: "Test API"
  version: "1.0.0"
  contact:
    name: Contact Name
    email: contact@example.com
    url: https://example.com/
servers:
- url: https://example.com
  description: Test Server
tags:
  - name: Generic
    description: Generic API
paths:
  /:
    get:
      operationId: getStuff
      summary: Get something
      tags: [ 'Generic' ]
      responses:
        '200':
          description: OK
```

Options file:
```yaml
httpsnippet: true
tocSummary: true
language_tabs:
  - shell: Shell
  - javascript: Javascript
  - java: Java
  - node: Node.js
language_clients:
  - shell: curl
  - javascript: fetch
  - java: okhttp
  - node: native
```

3. Markdown output:
````markdown
---
title: Test API
language_tabs:
  - shell: Shell
  - javascript: Javascript
  - java: Java
  - node: Node.js
toc_footers: []
includes: []
search: true
highlight_theme: darkula
headingLevel: 2

---

<h1 id="test-api">Test API v1.0.0</h1>

> Scroll down for code samples, example requests and responses. Select a language for code samples from the tabs above or the mobile navigation menu.

Base URLs:

* <a href="https://example.com">https://example.com</a>

Email: <a href="mailto:contact@example.com">Contact Name</a> Web: <a href="https://example.com/">Contact Name</a> 

<h1 id="test-api-generic">Generic</h1>

Generic API

## Get something

<a id="opIdgetStuff"></a>

> Code samples

```shell
curl --request GET \
  --url https://example.com/
```

```javascript
var data = null;

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === this.DONE) {
    console.log(this.responseText);
  }
});

xhr.open("GET", "https://example.com/");

xhr.send(data);
```

```java
OkHttpClient client = new OkHttpClient();

Request request = new Request.Builder()
  .url("https://example.com/")
  .get()
  .build();

Response response = client.newCall(request).execute();
```

```node
var http = require("https");

var options = {
  "method": "GET",
  "hostname": "example.com",
  "port": null,
  "path": "/",
  "headers": {}
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.end();
```

`GET /`

<h3 id="get-something-responses">Responses</h3>

|Status|Meaning|Description|Schema|
|---|---|---|---|
|200|[OK](https://tools.ietf.org/html/rfc7231#section-6.3.1)|OK|None|

<aside class="success">
This operation does not require authentication
</aside>
````

The issue is in the `node` code fence.

**Expected behavior**
I expect the node sample to show up only in the node tab. The highlighting is also broken in the node sample.

**Screenshots**
![image](https://user-images.githubusercontent.com/4928181/69953221-14681880-14f9-11ea-86ba-941b7b24bbe6.png)
![image](https://user-images.githubusercontent.com/4928181/69953578-d3bccf00-14f9-11ea-833c-6b491ba3e838.png)

**Versions**:
- Node.js (note only LTS versions are supported): 
```
❯ node -v
v12.13.1
```
**Additional context**

**Comment by Hydragyrum** [comment]
Ok I had to scrounge through the code for this one, but I had to use `javascript--node` to grab the httpsnippets nodejs client, and get the thing parsing properly.

the environment file follows:

```yaml
httpsnippet: true
tocSummary: true
language_tabs:
  - shell: Shell
  - javascript: Javascript
  - java: Java
  - javascript--node: Node.js
language_clients:
  - shell: curl
  - javascript: fetch
  - java: okhttp
  - javascript--node: native
```

I can consider this issue closed, but I think NodeJS is an exception that should be documented as well...
