### ISSUE TITLE
How do I make the Code Samples visible ?

### ISSUE THREAD

**Issue by girishchawla** [Mermade/widdershins#46]
I see [object Object] [ object Object] where I should see the name of a language on the top right. How do I make the language tab show the languages ? I am using petstore.json. I am trying to view the markdown in Whiteboard.

**Comment by MikeRalphson** [comment]
I think whiteboard doesn't (yet) support the feature of having separate display names for the language tabs.

You will probably need to override the `language_tabs` option from something like

```yaml
language_tabs:
  - shell: Shell
  - http: HTTP
  - javascript: JavaScript
  - javascript--nodejs: Node.JS
  - ruby: Ruby
  - python: Python
  - java: Java
```

```yaml
language_tabs:
  - shell
  - html
  - javascript
  - ruby
  - python
  - java
```

Let me know if you need any more information on doing that, or if it doesn't work for you, and I'll install whiteboard and have a look.
